{{- if not .Values.icebreaker.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icebreaker.fullname" . }}
  labels:
    {{- include "icebreaker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.icebreaker.secretKey }}
  {{ .Values.icebreaker.existingSecretKey }}: {{ .Values.icebreaker.secretKey | b64enc | quote }}
  {{- else }}
  # WARNING: No secret key provided. Generate one with: icebreaker keygen
  {{ .Values.icebreaker.existingSecretKey }}: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}
